### ISSUE TITLE
GCC should be upgrade.

### ISSUE THREAD

**Issue by barni2000** [DevTeamSCH/libanimeditor#1]
I think GCC 4.9 is little bit old.

https://github.com/DevTeamSCH/libanimeditor/blob/e45be2d3304466cdecfbaf6a0c8bf2a4098bde15/.travis.yml#L10

**Comment by fabledpig** [comment]
You are right, but in the project right now we are not using any CPP11+ feature, and GCC was CPP11 complete in version 4.9. If we use any CPP11+ feature we will update GCC accordingly.
